### ISSUE TITLE
"Kill" and "Awoo" categories do not work.

### ISSUE THREAD

**Issue by Zenyaria** [Waifu-pics/api#11]
The built in image finder returns with:
<img width="513" alt="Screenshot 2020-12-20 at 12 11 33" src="https://user-images.githubusercontent.com/66208171/102712941-95d54900-42bc-11eb-8961-a0f5a6f90de2.png">
and the API returns with:
<img width="461" alt="Screenshot 2020-12-20 at 12 12 19" src="https://user-images.githubusercontent.com/66208171/102712953-abe30980-42bc-11eb-8825-4f89a8abd811.png">

**Comment by Riku32** [comment]
This is normal, that occurs because currently there are no images under that endpoint uploaded, we are working on uploading some or you can upload some yourself and we will approve them.
