### ISSUE TITLE
api/sfw/kill don't work

### ISSUE THREAD

**Issue by Zaitooo** [Waifu-pics/api#12]
Hello, https://waifu.pics/api/sfw/kill don't work. He sending me `{"message":"there was an issue processing this request"}`

**Comment by Riku32** [comment]
This is because the kill endpoint does not have any images currently, if you would like to upload some this response will go away, I will message our moderators to upload some images

**Comment by Zenyaria** [comment]
Just want to note, I have been trying to upload the images, but there isn't any way of knowing if they've been submitted or not or approved. Could we get a small submit button?™

I had this same issue, but I tried uploading images, and I couldn't get how the system worked.

**Comment by Riku32** [comment]
I have approved your images, when you upload they go to the admin panel where some moderators have to approve images. We don't have a login page or anything for it for the user to know yet.
