### ISSUE TITLE
Question about API usage

### ISSUE THREAD

**Issue by guastallaigor** [Waifu-pics/api#13]
Hello, thank you for your project.

Just letting you know I'm using your API in a discord bot.
Link: https://github.com/guastallaigor/waifu-images-bot
I don't think it's going to be used a lot, and also it's deployed in heroku on a free tier plan, but still is it ok to use there?

Thank you.

**Comment by Riku32** [comment]
The API is fine to use for any project, just don't spam or abuse it with requests maliciously.
If you plan to modify or use the source code for the API or frontend please respect the licenses.
