### ISSUE TITLE
Issue with API

### ISSUE THREAD

**Issue by KaorukoMoeta** [Waifu-pics/api#14]
Using the code

`    if (command === 'waifu') {
        const waifu = new Discord.MessageEmbed()
        got('https://waifu.pics/api/many/sfw/waifu').then(response => {
            let content = JSON.parse(response.body);
            let permalink = content[0].data.children[0].data.permalink;
            let waifuUrl = `https://waifu.pics/${permalink}`;
            let waifuImage = content[0].data.children[0].data.url;
            waifu.setImage(`${waifuImage}`)
            waifu.setColor('#ffb9f4')
            waifu.setFooter(`Requested by ${message.author.user}`)
            waifu.setTimestamp()
            waifu.setAuthor(`waifu.pics`, `https://waifu.pics/`)
            message.channel.send(waifu)
        });
    };
`

ends up returning error `(node:9060) UnhandledPromiseRejectionWarning: HTTPError: Response code 405 (Method Not Allowed)`

I don't know what I have wrong in the code section but I may be doing everything completely wrong. Note: I'm pretty new to code and API usage.

Another question, what would the data inputs be for the image and url

**Comment by KaorukoMoeta** [comment]
EDIT: i removed the many from the link but it still shows  `TypeError: Cannot read property 'data' of undefined`

i will keep trying to fix it

**Comment by KaorukoMoeta** [comment]
EDIT: Changed code to
    if (command === 'waifu') {
        const waifu = new Discord.MessageEmbed()
        got('https://waifu.pics/api/sfw/megumin').then(response => {
            let content = JSON.parse(response.body);
            let waifuUrl = content[0].data.children[0].data.url;
            let waifuImage = content[0].data.children[0].data.url;
            waifu.setImage(`${waifuImage}`)
            waifu.setURL(`${waifuUrl}`)
            waifu.setColor('#ffb9f4')
            waifu.setFooter(`Requested by ${message.author.user}`)
            waifu.setTimestamp()
            waifu.setAuthor(`waifu.pics`, `https://waifu.pics/`)
            message.channel.send(waifu)
        });
    };

should still work the same, showing error `(node:18520) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined`

**Comment by Riku32** [comment]
First of all, this is an issue with your code, not an issue with your API. Second of all you are not using promises correctly at all in that first example, that code to set `content` is scoped in the promise and shouldn't be accessible anywhere else, even if you were setting an already set variable that .then and the actual request would execute after everything else, it would be a pending promise or nothing at all. Learn how promises and Javascript task queues work
