### ISSUE TITLE
Random category? 

### ISSUE THREAD

**Issue by kevinReynaud** [Waifu-pics/api#15]
I was doing tests in an android app and I liked it. 
Is there a way to get random categories? https://waifu.pics/api/sfw/random

**Comment by kevinReynaud** [comment]
I already did it through code, thanks for developing this api

**Comment by Riku32** [comment]
No problem, yeah random is not a priority as its supposed to be organized, just pick randomly out of the endpoints list. You can get the list at https://waifu.pics/api/endpoints
