### ISSUE TITLE
Only images? No gif?

### ISSUE THREAD

**Issue by RexiRexii** [Waifu-pics/api#16]
it would be great if the api had GIFs too, and not only pictures.

**Comment by rjworks** [comment]
Names too

**Comment by NekWasTaken** [comment]
Question is, why would there need to be gifs? It’s wifu.**pics*, as an pictures of wifus, there’s a chance you are talking about a different endpoint than what I’m thinking about but yeah. Also I agree that names should be included (if possible).

**Comment by Riku32** [comment]
I'm planning to rewrite the backend sooner or later. Right now I'm busy with life but in the future I plan to make a filtering feature so at the end of the URL you can put ?type=gif or ?type=image.
