### ISSUE TITLE
CORS-Origin issues

### ISSUE THREAD

**Issue by salmanthoriq95** [Waifu-pics/api#17]
I have trouble when I try to access your api with GET method with my only browser.

When I try to fetch ur api and try to resolve the promise it had return an error message that it not allowed because it have cors origin policy.

Can you fix it for me? Thx for advance

**Comment by Riku32** [comment]
`https://waifu.pics/api/sfw/waifu` Does this return a URL?

**Comment by Riku32** [comment]
Issue fixed with commit 02d6f6e
